export const research = [
  ['DwarfStar ds4','Runtime · MoE','https://dwarfstar.sh/','Selective quantization, SSD streaming and a tightly integrated local inference stack.','Quantizzazione selettiva, streaming da SSD e stack locale integrato.'],
  ['Colibrì','Runtime · Memory hierarchy','https://github.com/JustVugg/colibri','Treats storage, RAM and VRAM as one inference memory hierarchy for streamed MoE inference.','Tratta storage, RAM e VRAM come una sola gerarchia di memoria per MoE in streaming.'],
  ['exo','Distributed · Topology','https://github.com/exo-explore/exo','Connects heterogeneous devices into a topology-aware local AI cluster.','Collega dispositivi eterogenei in un cluster AI locale consapevole della topologia.'],
  ['WARP','Runtime · Paging','https://github.com/sqliteai/warp','Weight-aware paging with selected experts streamed from NVMe into a bounded cache.','Paging weight-aware con expert selezionati caricati da NVMe in una cache limitata.'],
  ['mlx-od-moe','Apple Silicon · MoE','https://github.com/kqb/mlx-od-moe','On-demand expert loading with memory mapping, caching and proactive prefetching.','Caricamento on-demand degli expert con memory mapping, cache e prefetch proattivo.'],
  ['MDI-LLM','Paper · Edge distribution','https://arxiv.org/abs/2505.18164','Partitions LLMs across low-power edge nodes with recurrent pipeline parallelism.','Partiziona LLM tra nodi edge a bassa potenza con pipeline parallelism ricorrente.'],
  ['WDMoE','Paper · Distributed MoE','https://arxiv.org/abs/2411.06681','Distributes experts across edge devices while jointly considering routing and communication latency.','Distribuisce gli expert tra dispositivi edge considerando routing e latenza di comunicazione.'],
  ['OD-MoE','Paper · Expert loading','https://arxiv.org/abs/2512.03927','Predicts expert use so weights can move before they are needed.','Predice l’uso degli expert per spostare i pesi prima che servano.'],
  ['MoE-SpeQ','Paper · Prefetch','https://arxiv.org/abs/2511.14102','Combines speculative decoding with proactive expert prefetching.','Combina speculative decoding e prefetch proattivo degli expert.'],
  ['MoE-Spec','Paper · Expert budgeting','https://arxiv.org/abs/2602.16052','Shows why speculative inference also needs explicit control of expert activation pressure.','Mostra perché l’inferenza speculativa richiede controllo esplicito della pressione sugli expert.'],
  ['d-Matrix','Hardware · In-memory compute','https://www.d-matrix.ai/wp-content/uploads/2024/11/d-Matrix-WhitePaper-Technical-FINAL.pdf','A memory-centric hardware direction that moves compute closer to model weights.','Una direzione hardware memory-centric che porta il calcolo più vicino ai pesi.'],
  ['Houmo','Hardware · PIM','https://www.houmo.cn/1/35/NewsDetails.html','A public signal toward DRAM-PIM and compute-in-memory for edge AI.','Un segnale pubblico verso DRAM-PIM e compute-in-memory per edge AI.']
].map(([name,kind,url,en,it])=>({name,kind,url,en,it}));

const common = {
  tagline:'Artificial Intelligence, Accessible.',
  chips:['MoE-first','Open research','Reproducible by default'],
  layers:[
    {n:'01',name:'MODEL',enTitle:'Change what must be loaded.',itTitle:'Cambiare ciò che deve essere caricato.',en:'Explore MoE structure, quantization, expert sharing, sparsity and architecture-level ideas while measuring quality.',it:'Esplorare struttura MoE, quantizzazione, condivisione degli expert, sparsità e idee architetturali misurando la qualità.'},
    {n:'02',name:'HARNESS',enTitle:'Make every token do less wasteful work.',itTitle:'Ridurre il lavoro sprecato per token.',en:'Optimize routing, caching, context handling, scheduling, speculative methods and orchestration around the model.',it:'Ottimizzare routing, cache, contesto, scheduling, metodi speculativi e orchestrazione attorno al modello.'},
    {n:'03',name:'SOFTWARE',enTitle:'Move weights and compute intelligently.',itTitle:'Muovere pesi e calcolo in modo intelligente.',en:'Build on llama.cpp, vLLM, MLX and emerging runtimes — or create the missing kernels, paging and distributed execution.',it:'Costruire sopra llama.cpp, vLLM, MLX e runtime emergenti — o creare kernel, paging e distribuzione mancanti.'},
    {n:'04',name:'OS',enTitle:'Give AI first-class control of the machine.',itTitle:'Dare all’AI controllo di prima classe sulla macchina.',en:'Study Linux, macOS, Windows or purpose-built layers for memory, I/O, scheduling, power and topology.',it:'Studiare Linux, macOS, Windows o layer dedicati per memoria, I/O, scheduling, potenza e topologia.'},
    {n:'05',name:'HARDWARE',enTitle:'Use what people can actually own.',itTitle:'Usare ciò che le persone possono davvero possedere.',en:'Start with consumer GPUs, Apple Silicon and mixed or recycled machines, then investigate purpose-built hardware where needed.',it:'Partire da GPU consumer, Apple Silicon e macchine miste o riciclate, poi esplorare hardware dedicato quando serve.'}
  ]
};

export const content = {
  en:{
    lang:'en',locale:'en_US',title:'AIXS — Frontier AI should fit on your machine',
    description:'AIXS is an open research initiative exploring models, harnesses, runtimes, operating systems and hardware as one system to bring frontier-class local AI closer to consumer machines.',
    nav:{thesis:'Thesis',stack:'The stack',research:'Research',mission:'Mission 01',join:'Join'},
    heroEyebrow:'OPEN RESEARCH INITIATIVE · COMMUNITY-BUILT',heroTitleA:'Frontier AI should fit',heroTitleB:'on your machine.',
    heroCopy:'AIXS explores how the entire local AI stack can be redesigned as one system — from model architecture to hardware — to bring frontier-class capability closer to affordable consumer machines.',
    tagline:common.tagline,joinCta:'Join the project',supportCta:'Support the research',heroNote:'Not a finished product. A research challenge worth attacking together.',chips:common.chips,
    problemEyebrow:'THE QUESTION',problemTitle:'AI keeps getting smarter. Access keeps getting narrower.',
    problemCopy:'Frontier models increasingly depend on huge memory capacity, high bandwidth and remote infrastructure. AIXS asks how much can be recovered by optimizing the whole stack together instead of treating every layer in isolation.',
    remote:'TODAY · REMOTE',local:'AIXS · LOCAL',remotePath:['Frontier model','Datacentre','API','You'],localPath:['Model','Harness','Software','OS','Hardware','You'],
    thesisEyebrow:'THE THESIS',thesisTitle:'Stop optimizing one layer at a time.',
    thesisCopy:'Model architecture, orchestration, runtime, operating system and hardware are coupled constraints. AIXS treats them as one optimization surface.',
    assemblyLabel:'SCROLL · SYSTEM ASSEMBLY',layers:common.layers.map(x=>({n:x.n,name:x.name,title:x.enTitle,body:x.en})),
    researchEyebrow:'SIGNALS FROM THE FRONTIER',researchTitle:'We start from evidence, not from zero.',
    researchCopy:'AIXS studies, reproduces and connects promising public work before inventing what is missing. The projects and papers below are independent work by their respective authors; citation does not imply affiliation.',
    researchHint:'Selected public work informing the AIXS research map',
    missionEyebrow:'MISSION 01 · BASELINE',missionTitle:'Make the starting point impossible to argue with.',
    missionCopy:'Our first target is a frontier-class open-weight MoE model. Before chasing breakthroughs, we will establish a reproducible consumer-hardware baseline and measure the system honestly.',
    missionSteps:[['01','Select','Choose an open-weight frontier-class MoE candidate and a defined consumer hardware class.'],['02','Reference','Establish model-quality and hosted/reference behavior without claiming unmeasured parity.'],['03','Reproduce','Run the strongest practical local baseline using existing open tooling.'],['04','Measure','Track quality, tokens/sec, time-to-first-token, RAM/VRAM, storage I/O and energy where measurable.'],['05','Optimize','Test one hypothesis at a time across the five layers with reproducible before/after evidence.'],['06','Publish','Release method, results, technical report and a demo others can reproduce.']],
    targetCards:[['QUALITY','Preserve as much of the reference model’s intelligence as technically possible.'],['PERFORMANCE','Push local responsiveness aggressively without publishing unmeasured parity claims.'],['ACCESS','Target consumer-grade machines rather than datacentre-only hardware.']],
    joinEyebrow:'BUILD IT WITH US',joinTitle:'Bring what you know. Or the drive to learn.',joinCopy:'We are looking for researchers, ML engineers, systems builders, hardware people, benchmark obsessives and technically curious contributors. Deep experience helps; motivation, rigor and the ability to learn are valid entry points.',
    joinTracks:['Model / ML research','Harness / agents','Runtime / systems','OS / scheduling','Hardware','Benchmarking','Docs / community'],
    levels:['Beginner / motivated to learn','Intermediate','Experienced','Research / specialist'],availability:['A few hours / month','1–3 hours / week','4–8 hours / week','8+ hours / week','Project-based / flexible'],
    joinForm:{title:'Join AIXS',intro:'Tell us where you could contribute. We are assembling the first working group.',name:'Name',email:'Email',profile:'GitHub or LinkedIn',track:'Primary area',level:'Experience level',contribution:'What would you like to explore or contribute?',availability:'Time you can realistically contribute',consent:'I agree that AIXS may use this information only to contact me about participation in the initiative.',submit:'Send application',success:'Application received. Thank you — we will review it and get back to you.',endpoint:'The form is not connected yet. Configure JOIN_FORM_ENDPOINT before launch.'},
    supportEyebrow:'SUPPORT THE RESEARCH',supportTitle:'Fund the question, not the hype.',supportCopy:'AIXS needs more than money. Hardware, compute access, technical collaboration and research partnerships can shorten the path from hypothesis to reproducible evidence.',
    supportTypes:[['Funding','Help cover hardware, experiments, benchmarks and contributor work.'],['Hardware','Provide machines, accelerators, memory or storage for reproducible tests.'],['Compute','Offer cloud or lab capacity for reference runs and controlled comparisons.'],['Research / industry','Collaborate on systems, models, hardware or measurement.']],
    sponsorForm:{title:'Start a conversation',org:'Organisation / name',email:'Contact email',type:'How could you contribute?',message:'Tell us what you have in mind',consent:'I agree that AIXS may use this information only to respond about research support or partnership.',submit:'Contact AIXS',success:'Message received. Thank you — we will get back to you.',endpoint:'The sponsor form is not connected yet. Configure SPONSOR_FORM_ENDPOINT before launch.'},
    faqEyebrow:'CLEAR ANSWERS',faqTitle:'What AIXS is — and what it is not.',faqs:[['Is AIXS already a company?','No. It starts as a community-led research initiative. A commercial path may be considered later if real breakthroughs justify it.'],['Will everything be open source?','Research methods, public evidence and reproducible benchmarks are intended to be open. Future components may use different licensing if needed for sustainability.'],['Do I need to be an expert?','No. Experienced people are important, but motivated beginners who can learn, reproduce experiments and document results rigorously are welcome.'],['Which model will you start with?','A frontier-class open-weight Mixture-of-Experts model. The exact candidate remains open until the first working group evaluates reproducibility and hardware fit.'],['Are you affiliated with the projects cited above?','No, unless explicitly stated. They are cited because their public work is relevant to the research space.']],
    footerNote:'Open research toward more accessible local frontier AI.',privacy:'Privacy',github:'GitHub',language:'IT',langHref:'/it/'
  },
  it:{
    lang:'it',locale:'it_IT',title:'AIXS — L’AI di frontiera dovrebbe stare sulla tua macchina',
    description:'AIXS è un’iniziativa di ricerca aperta che studia modello, harness, runtime, sistema operativo e hardware come un unico sistema per avvicinare l’AI locale di frontiera alle macchine consumer.',
    nav:{thesis:'Tesi',stack:'Lo stack',research:'Ricerca',mission:'Missione 01',join:'Partecipa'},
    heroEyebrow:'INIZIATIVA DI RICERCA APERTA · COSTRUITA DALLA COMMUNITY',heroTitleA:'L’AI di frontiera dovrebbe stare',heroTitleB:'sulla tua macchina.',
    heroCopy:'AIXS esplora come riprogettare l’intero stack dell’AI locale come un unico sistema — dall’architettura del modello all’hardware — per avvicinare capacità di frontiera a macchine consumer accessibili.',
    tagline:common.tagline,joinCta:'Partecipa al progetto',supportCta:'Sostieni la ricerca',heroNote:'Non è un prodotto finito. È una sfida di ricerca da affrontare insieme.',chips:['MoE-first','Ricerca aperta','Riproducibile per default'],
    problemEyebrow:'LA DOMANDA',problemTitle:'L’AI diventa più potente. L’accesso diventa più stretto.',problemCopy:'I modelli di frontiera dipendono sempre più da enormi capacità di memoria, banda elevata e infrastruttura remota. AIXS chiede quanto possiamo recuperare ottimizzando l’intero stack insieme.',
    remote:'OGGI · REMOTO',local:'AIXS · LOCALE',remotePath:['Modello di frontiera','Datacenter','API','Tu'],localPath:['Modello','Harness','Software','OS','Hardware','Tu'],
    thesisEyebrow:'LA TESI',thesisTitle:'Smettere di ottimizzare un livello alla volta.',thesisCopy:'Architettura del modello, orchestrazione, runtime, sistema operativo e hardware sono vincoli interdipendenti. AIXS li tratta come un’unica superficie di ottimizzazione.',
    assemblyLabel:'SCROLL · ASSEMBLAGGIO DEL SISTEMA',layers:common.layers.map(x=>({n:x.n,name:x.name,title:x.itTitle,body:x.it})),
    researchEyebrow:'SEGNALI DALLA FRONTIERA',researchTitle:'Partiamo dalle evidenze, non da zero.',researchCopy:'AIXS studia, riproduce e collega lavori pubblici promettenti prima di inventare ciò che manca. I progetti e i paper citati sono indipendenti; la citazione non implica affiliazione.',researchHint:'Una selezione del lavoro pubblico che alimenta la mappa di ricerca AIXS',
    missionEyebrow:'MISSIONE 01 · BASELINE',missionTitle:'Rendere il punto di partenza impossibile da contestare.',missionCopy:'Il primo target è un modello MoE open-weight di frontiera. Prima di inseguire breakthrough, costruiremo una baseline riproducibile su hardware consumer e misureremo il sistema con onestà.',
    missionSteps:[['01','Selezionare','Scegliere un MoE open-weight di frontiera e una classe hardware consumer definita.'],['02','Riferimento','Stabilire qualità e comportamento hosted/reference senza dichiarare parità non misurate.'],['03','Riprodurre','Eseguire la migliore baseline locale pratica con tooling aperto disponibile.'],['04','Misurare','Tracciare qualità, token/sec, time-to-first-token, RAM/VRAM, I/O storage ed energia dove possibile.'],['05','Ottimizzare','Testare un’ipotesi alla volta sui cinque livelli con evidenze riproducibili.'],['06','Pubblicare','Rilasciare metodo, risultati, report tecnico e demo riproducibile.']],
    targetCards:[['QUALITÀ','Preservare il più possibile l’intelligenza del modello di riferimento.'],['PERFORMANCE','Spingere la reattività locale senza pubblicare dichiarazioni di parità non misurate.'],['ACCESSO','Puntare a macchine consumer e non solo hardware da datacenter.']],
    joinEyebrow:'COSTRUISCILO CON NOI',joinTitle:'Porta ciò che sai. Oppure la voglia di imparare.',joinCopy:'Cerchiamo ricercatori, ML engineer, system builder, persone hardware, fanatici dei benchmark e contributor tecnicamente curiosi. Esperienza, motivazione, rigore e capacità di imparare sono tutti validi punti di ingresso.',
    joinTracks:['Modello / ricerca ML','Harness / agenti','Runtime / sistemi','OS / scheduling','Hardware','Benchmarking','Documentazione / community'],levels:['Principiante / motivato a imparare','Intermedio','Esperto','Ricerca / specialista'],availability:['Qualche ora / mese','1–3 ore / settimana','4–8 ore / settimana','8+ ore / settimana','Per progetto / flessibile'],
    joinForm:{title:'Partecipa ad AIXS',intro:'Raccontaci dove potresti contribuire. Stiamo assemblando il primo gruppo di lavoro.',name:'Nome',email:'Email',profile:'GitHub o LinkedIn',track:'Area principale',level:'Livello di esperienza',contribution:'Cosa vorresti esplorare o contribuire?',availability:'Tempo che puoi realisticamente dedicare',consent:'Accetto che AIXS utilizzi queste informazioni solo per contattarmi sulla partecipazione all’iniziativa.',submit:'Invia candidatura',success:'Candidatura ricevuta. Grazie — la esamineremo e ti ricontatteremo.',endpoint:'Il modulo non è ancora collegato. Configura JOIN_FORM_ENDPOINT prima del lancio.'},
    supportEyebrow:'SOSTIENI LA RICERCA',supportTitle:'Finanzia la domanda, non l’hype.',supportCopy:'AIXS ha bisogno di più del denaro. Hardware, accesso al compute, collaborazione tecnica e partnership di ricerca possono ridurre il percorso tra ipotesi ed evidenza riproducibile.',
    supportTypes:[['Funding','Aiuta a coprire hardware, esperimenti, benchmark e lavoro dei contributor.'],['Hardware','Metti a disposizione macchine, acceleratori, memoria o storage per test riproducibili.'],['Compute','Offri capacità cloud o di laboratorio per reference run e confronti controllati.'],['Ricerca / industria','Collabora su sistemi, modelli, hardware o misurazione.']],
    sponsorForm:{title:'Iniziamo una conversazione',org:'Organizzazione / nome',email:'Email di contatto',type:'Come potresti contribuire?',message:'Raccontaci cosa hai in mente',consent:'Accetto che AIXS utilizzi queste informazioni solo per rispondere su supporto o partnership.',submit:'Contatta AIXS',success:'Messaggio ricevuto. Grazie — ti ricontatteremo.',endpoint:'Il modulo sponsor non è ancora collegato. Configura SPONSOR_FORM_ENDPOINT prima del lancio.'},
    faqEyebrow:'RISPOSTE CHIARE',faqTitle:'Cos’è AIXS — e cosa non è.',faqs:[['AIXS è già un’azienda?','No. Nasce come iniziativa di ricerca guidata dalla community. Un percorso commerciale potrà essere valutato più avanti se emergeranno breakthrough reali.'],['Sarà tutto open source?','Metodi di ricerca, evidenze pubbliche e benchmark riproducibili sono pensati per essere aperti. Componenti futuri potranno avere licenze diverse se necessario per la sostenibilità.'],['Devo essere un esperto?','No. Servono persone esperte, ma sono benvenuti anche principianti motivati che sappiano imparare, riprodurre esperimenti e documentare risultati con rigore.'],['Con quale modello inizierete?','Un modello Mixture-of-Experts open-weight di frontiera. Il candidato esatto resta aperto finché il primo gruppo di lavoro non valuterà riproducibilità e compatibilità hardware.'],['Siete affiliati ai progetti citati sopra?','No, salvo indicazione esplicita. Sono citati perché il loro lavoro pubblico è rilevante per lo spazio di ricerca.']],
    footerNote:'Ricerca aperta verso un’AI locale di frontiera più accessibile.',privacy:'Privacy',github:'GitHub',language:'EN',langHref:'/'
  }
};
